var combinations = [
"aba a abba abaaa abbb abbaa bbb aba bbb" ,
"dddcd ccdd c dddd ccccd cccd cddc ddd c" ,
"efff fffe eff feeeef ffeefe feee fefe fef",
"ghhgh ghgh hggg hghghh hgghh hghg h hggh",
"iijjj jiij jj ijii ijj jijjji ii jijiii ji",
"kk lklk lkllk kllklk klkk kll kkkk kkl kl",
"mmmnmn mmmmn nmnnm mmmmn mmn mnnm nn nnm",
"oooo opoop opoo pp oopp opopo op opo oopp",
"qrr rqr rqrq qrqq rq qr rqqqqrrq qrrrqq",
"stst sss st st sstts ttst tt ststt tttss",
"vuuvuuu uuuuu uu uvvuvuv u uvvvu uuvu vuu",
"wxwxw wwwww wwx xwx xwwxw xxw wx wwwwxx",
"yzz yz zzzyz yyzz yzz zyyy yzzz yyzz zzz",
"asffa saaf sasa daaafs aaf daaf affda",
"gghl llkj hgh gkkkh lgl llljg hhhh lj",
"rqeqwt erq teee qtt wrwrr rtq tqq ttttq",
"upyyu oyu uiiu iou popy yuu uyop uiyi",
"cxvvx xvx xzcxcxc vxc cc cvvvv zv vxxz",
"zsqq sqqss aqqsq zaq qsazs sssss zzq",
"ettveve vve dvdvv tcec vtedddce devv tec",
"nbffufjn bjffj nunj jjjjju fjb jnf fjfb",
"ll kk ppin nknlp lpp plkpi l ikpp klnnn",
"hhvgr hmvg mrmvr rm vhvv vmgvh vvhrr vvm",
"eoau oioi ueu aauu eiu uioe aaaa uoe",
"msksvnk kk sskmb bm svvvsb nnmn mkm ssn",

];
