const senset = ['A bird in the hand is worth two in the bush',
'Caught between a rock and a hard place' ,
'Closing the barn door after the horse escapes' ,
 'You go to holiday every summer' ,
'Friends are flowers in the garden of life' ,
   'The grass is always greener on the other side' ,
    'Just staying one day ahead of yesterday' ,
    'Lie down with dogs and wake up with fleas',
    'The sharper the berry, the sweeter the wine' ,
  'The squeaky wheel gets the grease',
  'The stronger the breeze the stronger the trees',
'My daughter does the laundry',
'All work and no play robs one of some fun in life',
  'Your car is out of date as soon as it is paid for',
  'Mary brushes her teeth twice a day',
  'Thank you for taking the time to apply for our retail manager',
  'We can’t refund your money unless you include a receipt',
  'My Dad never works on the weekends',
  'Tomorrow early morning first I go to morning walk',
  'He wanted to bring peace to his kingdom',
  'There were many others who wanted to become king',
  'They started plotting against him',
  'Then they started killing those trusted friends',
  'War does not bring anything good to the common people',
  'It only brings sorrow and dismay',
  'A great chaos broke out in the kingdom',
  'People were anxious and unhappy'
];
